
services:

  nginx:
    build: .
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/app
    ports:
      - 80:80
      - 443:443
    networks:
      - server-net

networks:
  server-net:
    driver: bridge

