build:
	docker-compose up --build -d

up:
	docker-compose up -d


logs:
	docker-compose logs nginx


down:
	docker-compose down

ls: 
	docker-compose ps -a

prune:
	docker system prune

conn:
	docker compose exec -it nginx bash
